// product-list.js
const productsInventory = [
    {
        id: "1",
        name: "NIKE AIR MAX DN",
        category: "Lifestyle shoes",
        tagline: "SUSTAINABLE MATERIALS",
        description: "Inspired by the Air Max icons of the past, the Pulse Roam takes performance into a lifestyle dimension. Tough materials and utilitarian aesthetics combine with a point-loaded Air unit for bounce that lasts all day.",
        price: "$160.00",
        image: "img/nike air max dn.png",         
        subImg1: "img/nike air max dn1.jpg",       
        subImg2: "img/nike air max dn2.jpg",       
        subImg3: "img/nike air max dn3.jpg"        
    },
    {
        id: "2",
        name: "NIKE DUNK LOW",
        category: "Men's Shoes",
        tagline: "SUSTAINABLE MATERIALS",
        description: "Created for the hardwood but taken to the streets, the Nike Dunk Low Retro returns with crisp overlays and original team colors.",
        price: "$115",
        image: "img/Dunk low.png",   
        subImg1: "img/Dunk low 1.jpg", 
        subImg2: "img/Dunk low 2.jpg", 
        subImg3: "img/Dunk low 3.jpg"  
    },
    {
        id: "3",
        name: "Nike Pegasus 41",
        tagline: "Road Running Shoes",
        description: "For over four decades, the Pegasus line has been the dependable workhorse of the running world, and the Nike Pegasus 41 takes that legacy to new heights. Built for runners who demand consistency, comfort, and a little extra spring in their step, this iteration introduces an upgraded, highly breathable engineered mesh upper that molds perfectly to your foot while keeping things cool when the miles heat up. At its core, the Pegasus 41 pairs Nikes ultra-responsive ReactX foam midsole with dual Zoom Air units in the forefoot and heel. This combination delivers incredible energy return, dampening harsh road impacts and smoothly propelling you into your next stride. Whether you are crushing an early morning 5K or training for your next marathon, the signature waffle-inspired rubber outsole provides exceptional grip on the tarmac. Lace up and feel the perfect balance of secure containment and lightweight freedom.",
        price: "$140",
        image: "img/Nike Pegasus.jpg",
        subImg1: "img/Nike Pegasus1.jpg",
        subImg2: "img/Nike Pegasus2.jpg",
        subImg3: "img/Nike Pegasus3.jpg",
    },
    {
        id: "4",
        name: "Nike Air Force 1 '07",
        tagline: "Men's Shoes",
        description: "A hoops legend turned cultural icon, the Nike Air Force 1 '07 transcends trends. This modern take on the 1982 classic retains everything that made it a masterpiece: crisp leather edges, a bold profile, and just the right amount of court-inspired flash. The premium leather upper breaks in beautifully over time, giving you a custom feel and a sleek look that pairs effortlessly with everything from stacked cargo pants to classic denim. Designed originally for performance basketball, the encapsulated Nike Air cushioning in the heel provides lightweight, all-day comfort. The padded, low-cut collar adds a sleek silhouette while feeling soft around the ankle, and the non-marking rubber outsole features the iconic pivot-circle tread pattern for time-tested traction. Clean, timeless, and effortlessly cool, the Air Force 1 '07 isn't just a sneaker—it's a wardrobe essential.",
        price: "$115",
        image: "img/nike air force 1.png",
        subImg1: "img/nike air force 1'1 .jpg",
        subImg2: "img/nike air force 1'2 .jpg",
        subImg3: "img/nike air force 1'3 .jpg",
    },
    {
        id: "5",
        name: "Nike Blazer Mid '77",
        tagline: "Vintage Life Style",
        description: "Capture the rebellious spirit of the 1970s with the Nike Blazer Mid '77. Originally built for the basketball court, this sneaker has evolved into a staple for skaters, artists, and sneakerheads alike. It features a crisp leather and synthetic upper, accented by throwback hairy-suede overlays on the toe and sides that add rich texture and that highly sought-after vintage aesthetic. The exposed foam tongue is a direct nod to Nike’s early heritage, giving the shoe an authentic, old-school DIY feel. Underneath, a vulcanized construction fuses the outsole directly to the midsole for a streamlined, low-profile look that offers excellent board feel and flexibility. Finished with a classic herringbone rubber sole for reliabl",
        price: "$105",
        image: "img/Nike blazer mid '77.png",
        subImg1: "img/Nike Blazer Mid '77 1.jpg",
        subImg2: "img/Nike Blazer Mid '77 2.jpg",
        subImg3: "img/Nike Blazer Mid '77 3.jpg",
    },
    {
        id: "6",
        name: "Nike Metcon 9",
        tagline: "Training Shoes",
        description: "When your workout demands everything you’ve got, the Nike Metcon 9 delivers the unwavering stability and durability to match your drive. Engineered specifically for athletes, weightlifters, and fitness enthusiasts, the Metcon 9 features an enlarged Hyperlift plate in the heel. This rigid plate forces weight down and out, providing incredible stability and a solid foundation during heavy lifts like squats, cleans, and deadlifts. The upper is reinforced with a lightweight, breathable textile wrapped in a durable, multi-directional haptic print to resist abrasions from rope climbs and wall exercises. For those grueling cardio intervals, the dual-density midsole—firm on the outside and soft on the inside—provides responsive cushioning without sacrificing stability. Complete with an extended rubber rope wrap that climbs up the midfoot for ultimate grip, the Metcon 9 is built to withstand the absolute toughest gym sessions.",
        price: "$150",
        image: "img/Nike metcon 9.png",
        subImg1: "img/Nike metcon 9'1.jpg",
        subImg2: "img/Nike metcon 9'2.jpg",
        subImg3: "img/Nike metcon 9'3.jpg",
    },
        {
        id: "7",
        name: "Nike Sportswear Tech Fleece",
        tagline: "Modern warmth for the next generation",
        description: "Revolutionizing casual comfort, Nike Sportswear Tech Fleece delivers impressive warmth without the bulk of traditional heavy fabrics. This premium, lightweight fleece is smooth on both sides, utilizing a tri-layer construction where a plush layer of foam is micro-knitted between cotton jersey fabrics. The result is a clean, structured silhouette that holds its shape while offering total freedom of movement. Instantly recognizable by its iconic bonded zippered pockets and clean geometric seam lines, Tech Fleece bridges the gap between high-end tailoring and athletic lounge gear. Whether you are wearing the full-zip Windrunner hoodie or the tapered joggers, it provides a streamlined look that looks sharp in the city and feels incredibly soft against the skin.",
        price: "$80",
        image: "img/nike tech flees.png",
        subImg1: "",
        subImg2: "",
        subImg3: "",
    },
    {
        id: "8",
        name: "Ekiden Collection",
        tagline: "Engineered for the long run.",
        description: "The Nike Ekiden Collection is a stunning tribute to Japan’s legendary multi-stage relay races, where teams push the limits of human endurance. Applying striking, fiery graphics and specialized color palettes to Nike's elite running shoes (like the Alphafly, Vaporfly, and Pegasus), this collection embodies the grit, camaraderie, and intense speed of race day. Each shoe in the pack retains its world-class performance tech—such as responsive ZoomX foam and snappy carbon fiber plates—but updates the visuals with deep cultural nods. From subtle split-toe motifs to color gradients representing the transition from sunrise to sunset during the grueling race, the Ekiden Collection turns high-performance footwear into moving art.",
        price: "$100",
        image: "img/Ekiden Collection.jpg",
        subImg1: "",
        subImg2: "",
        subImg3: "",
    },
    {
        id: "9",
        name: "Nike Pro BaseLayers",
        tagline: "The foundation of every workout.",
        description: "The foundation of every great workout, Nike Pro BaseLayers are engineered to help athletes perform at their absolute peak. Made from a highly elastic, durable polyester blend, these shirts, tights, and shorts hug the body like a second skin. This compression fit not only supports major muscle groups to minimize fatigue, but also ensures your clothing never gets in the way of explosive movements. Equipped with signature Dri-FIT technology, the fabric actively pulls sweat away from your skin to the surface of the garment, where it evaporates quickly. Strategic mesh panels are integrated into high-heat zones—like the underarms and lower back—to maximize airflow. Whether used to stay warm on a crisp morning field or to manage sweat during a heavy lifting session, Nike Pro keeps you dry, cool, and completely dialed in.",
        price: "$70",
        image: "img/Nike Pro BaseLayers.jpg",
        subImg1: "",
        subImg2: "",
        subImg3: "",
    },
    {
        id: "10",
        name: "AIR MAX ALPHA",
        tagline: "Men's Training Shoes",
        description: "dominate your toughest gym days, the Nike Air Max Alpha blends performance lifting stability with everyday comfort. Built with a wide, flat base and an enhanced rubber tread wrap that extends up the side, this shoe locks your foot in place for heavy squats, lunges, and overhead presses. The durable mesh upper is reinforced with tough skins and overlays, resisting abrasions no matter how intensely you train. The standout feature is the visible Max Air unit embedded in the heel. Paired with a supportive foam midsole, it provides responsive cushioning that absorbs impact during box jumps, agility drills, or sudden explosive movements, without compromising the solid foundation needed for weightlifting. It is the ideal crossover shoe for the athlete who transitions seamlessly from the squat rack to the turf.",
        price: "$145",
        image: "img/air max alpha.jpg",
        subImg1: "",
        subImg2: "",
        subImg3: "",
    },
    {
        id: "11",
        name: "PEGASUS 40",
        tagline: "Men's Running shoes",
        description: "Celebrating a legendary milestone, the Nike Pegasus 40 delivers its signature springy, neutral ride with a renewed focus on internal comfort. Known affectionately as the workhorse with wings this version features a redesigned single-layer mesh upper that enhances breathability while mapping beautifully to the unique contours of your foot. An updated midfoot band safely cradles the arch, offering a highly secure feel without pinching. The cushioning pairs two Zoom Air units (one in the forefoot, one in the heel) with lightweight Nike React foam. This combination delivers a smooth, responsive transition from heel to toe, turning road impacts into forward momentum. Exceptionally durable and incredibly consistent, the Pegasus 40 remains the go-to choice for runners of all levels who just want to lace up and log miles without a second thought.",
        price: "$130",
        image: "img/PEGASUS 40.jpg",
        subImg1: "",
        subImg2: "",
        subImg3: "",
    },
    {
        id: "12",
        name: "DUNK HIGH PRO",
        tagline: "Men's Basketball Shoes",
        description: "Steeped in subcultural history, the Nike Dunk High Pro (often curated under the Nike SB skate line) updates the legendary 1985 basketball silhouette for maximum durability and board control. Featuring a supportive high-top collar, this sneaker is constructed from premium leather, suede, or canvas overlays that are double-stitched to handle the heavy scuffs of skateboarding and daily city grinding. Unlike its lifestyle counterparts, the Pro edition includes a specialized Zoom Air unit embedded in the sockliner, offering low-profile impact protection during heavy landings. The padded mesh tongue and collar provide plush ankle support, while the vulcanized rubber outsole features a classic hoops pivot circle for incredible multidirectional grip. It’s a flawless blend of retro varsity aesthetics and rugged, modern functionality.",
        price: "$125",
        image: "img/DUNK HIGH PRO.jpg",
        subImg1: "",
        subImg2: "",
        subImg3: "",
    },
    {
        id: "13",
        name: "NIKE UNIVERSA",
        tagline: "Firm support high waist Capris",
        description: "",
        price: "$90",
        image: "img/nike universa.jpg",
        subImg1: "",
        subImg2: "",
        subImg3: "",
    },
        {
        id: "14",
        name: "NIKE Go",
        tagline: "Firm support high waist leggings",
        description: "",
        price: "$90",
        image: "img/Nike go.jpg",
        subImg1: "",
        subImg2: "",
        subImg3: "",
    },
    {
        id: "15",
        name: "NIKE UNIVERSA",
        tagline: "Gental support high waist leggings",
        description: "",
        price: "$80",
        image: "img/nike zenvy.jpg",
        subImg1: "",
        subImg2: "",
        subImg3: "",
    },
        {
        id: "16",
        name: "NIKE DYNAMO GO",
        tagline: "YOUNGER KID EASY ON-0FF",
        description: "",
        price: "$80",
        image: "img/nike zenvy.jpg",
        subImg1: "",
        subImg2: "",
        subImg3: "",
    },
    {
        id: "17",
        name: "NIKE FLEX PLUS 2",
        tagline: "OLDER KIDS' TRAINING",
        description: "",
        price: "$80",
        image: "img/nike zenvy.jpg",
        subImg1: "",
        subImg2: "",
        subImg3: "",
    },
    {
        id: "18",
        name: "NIKE STAR RUNNER",
        tagline: "KIDS' CASUAL",
        description: "",
        price: "$80",
        image: "img/nike zenvy.jpg",
        subImg1: "",
        subImg2: "",
        subImg3: "",
    },
];